"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Loader2, Send } from "lucide-react";
import { supabase } from "../../supabase";

type Message = { id: number; sender_id: string; content: string; created_at: string; read_at: string | null };
export default function ConversationPage({ id, language }: { id: string; language: "en" | "pl" }) {
  const [messages, setMessages] = useState<Message[]>([]); const [userId, setUserId] = useState<string | null>(null); const [content, setContent] = useState(""); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState("");
  const t = language === "pl" ? { back: "Wiadomości", title: "Rozmowa", placeholder: "Napisz wiadomość…", send: "Wyślij wiadomość", login: "Zaloguj się, aby zobaczyć rozmowę.", error: "Nie udało się pobrać rozmowy.", sendError: "Nie udało się wysłać wiadomości." } : { back: "Messages", title: "Conversation", placeholder: "Write a message…", send: "Send message", login: "Sign in to view this conversation.", error: "Could not load this conversation.", sendError: "Could not send the message." };
  async function load() { const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) { setError(t.login); setLoading(false); return; } setUserId(session.user.id); const { data, error } = await supabase.from("messages").select("id, sender_id, content, created_at, read_at").eq("conversation_id", id).order("created_at"); if (error) setError(t.error); else { setMessages(data ?? []); await supabase.rpc("mark_conversation_read", { target_conversation_id: id }); } setLoading(false); }
  // `load` is intentionally invoked after mount and already closes over this route's id/language.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const timeoutId = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timeoutId); }, [id, language]);
  async function submit(event: FormEvent) { event.preventDefault(); const text = content.trim(); if (!text || !userId) return; setSending(true); setError(""); const { error } = await supabase.from("messages").insert({ conversation_id: id, sender_id: userId, content: text }); setSending(false); if (error) { setError(t.sendError); return; } setContent(""); await load(); }
  const backHref = language === "pl" ? "/messages" : "/en/messages";
  return <main className="min-h-screen bg-[#F7F4FB] px-4 py-8 text-[#17142E] sm:px-6 sm:py-12"><section className="mx-auto max-w-3xl"><Link href={backHref} className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[#7438B7]"><ArrowLeft size={17} />{t.back}</Link><div className="mt-4 rounded-2xl border border-[#E8E1F0] bg-white p-5 shadow-[0_18px_55px_rgba(51,36,82,0.09)] sm:p-7"><h1 className="text-2xl font-bold">{t.title}</h1>{loading ? <p className="mt-6 flex items-center gap-2 text-[#6E6582]"><Loader2 className="animate-spin" size={18} />{language === "pl" ? "Ładowanie…" : "Loading…"}</p> : <><div className="mt-6 grid gap-3">{messages.map((message) => <article key={message.id} className={`max-w-[85%] rounded-2xl p-3 text-sm leading-6 ${message.sender_id === userId ? "ml-auto bg-[#7438B7] text-white" : "bg-[#F4EEF9] text-[#332B4D]"}`}><p className="whitespace-pre-wrap break-words">{message.content}</p><time className="mt-1 block text-xs opacity-70">{new Intl.DateTimeFormat(language === "pl" ? "pl-PL" : "en-GB", { dateStyle: "short", timeStyle: "short" }).format(new Date(message.created_at))}</time></article>)}</div><form onSubmit={submit} className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto]"><label className="sr-only" htmlFor="message-content">{t.placeholder}</label><textarea id="message-content" value={content} onChange={(event) => setContent(event.target.value)} maxLength={2000} required placeholder={t.placeholder} className="min-h-12 w-full resize-y rounded-xl border border-[#DED6EA] px-4 py-3 outline-none focus:border-[#A875D2]" /><button disabled={sending} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#7438B7] px-5 text-sm font-semibold text-white disabled:opacity-60">{sending ? <Loader2 size={17} className="animate-spin" /> : <Send size={17} />}{t.send}</button></form></>}{error ? <p role="status" className="mt-4 text-sm text-red-700">{error}</p> : null}</div></section></main>;
}
