"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Loader2 } from "lucide-react";
import { supabase } from "../supabase";

export default function AddWantedPage({ language }: { language: "en" | "pl" }) {
  const [userId, setUserId] = useState<string | null>(null); const [brand, setBrand] = useState(""); const [yarn, setYarn] = useState(""); const [color, setColor] = useState(""); const [lot, setLot] = useState(""); const [skeins, setSkeins] = useState(""); const [notes, setNotes] = useState(""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const t = language === "pl" ? { title: "Dodaj, czego szukasz", intro: "Opisz włóczkę, której potrzebujesz. Inne osoby będą mogły napisać do Ciebie przez Dyeloty.", login: "Zaloguj się, aby dodać ogłoszenie „Szukam”.", brand: "Marka", yarn: "Nazwa włóczki", color: "Kolor / numer koloru", lot: "Dye lot (opcjonalnie)", skeins: "Ilość, której szukasz", notes: "Dodatkowe informacje", submit: "Opublikuj ogłoszenie", required: "Uzupełnij markę, nazwę włóczki, kolor i ilość.", error: "Nie udało się dodać ogłoszenia.", success: "Ogłoszenie „Szukam” zostało opublikowane.", back: "Wróć do ogłoszeń" } : { title: "Post a yarn request", intro: "Describe the yarn you need. Other users can contact you through Dyeloty.", login: "Sign in to post a yarn request.", brand: "Brand", yarn: "Yarn name", color: "Color / color number", lot: "Dye lot (optional)", skeins: "Quantity needed", notes: "Additional information", submit: "Post request", required: "Enter the brand, yarn name, color, and quantity.", error: "Could not post the request.", success: "Your yarn request has been posted.", back: "Back to requests" };
  useEffect(() => { void supabase.auth.getSession().then(({ data: { session } }) => setUserId(session?.user?.id ?? null)); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); const count = Number.parseInt(skeins, 10); if (!userId) { setMessage(t.login); return; } if (!brand.trim() || !yarn.trim() || !color.trim() || !Number.isFinite(count) || count < 1) { setMessage(t.required); return; } setLoading(true); const { error } = await supabase.from("listings").insert({ brand: brand.trim(), yarn_name: yarn.trim(), color: color.trim(), dyelot: lot.trim() || null, skeins: count, description: notes.trim() || null, listing_type: "wanted", status: "available", user_id: userId, contact: null, type: null, country: null, image_url: null }); setLoading(false); if (error) { console.error("Could not create wanted listing", error); setMessage(t.error); return; } setMessage(t.success); setBrand(""); setYarn(""); setColor(""); setLot(""); setSkeins(""); setNotes(""); }
  const backHref = language === "pl" ? "/looking" : "/en/looking";
  return <main className="min-h-screen bg-[#F7F4FB] px-4 py-8 text-[#17142E] sm:px-6 sm:py-12"><section className="mx-auto max-w-2xl"><Link href={backHref} className="text-sm font-semibold text-[#7438B7]">← {t.back}</Link><form onSubmit={submit} className="mt-5 rounded-2xl border border-[#E8E1F0] bg-white p-6 shadow-[0_18px_55px_rgba(51,36,82,0.09)] sm:p-8"><h1 className="text-3xl font-bold">{t.title}</h1><p className="mt-3 leading-6 text-[#6E6582]">{t.intro}</p>{userId ? <div className="mt-6 grid gap-5">{[[t.brand, brand, setBrand, false], [t.yarn, yarn, setYarn, false], [t.color, color, setColor, false], [t.lot, lot, setLot, true], [t.skeins, skeins, setSkeins, false]].map(([label, value, setter, optional]) => <label key={String(label)} className="block text-sm font-semibold text-[#514A67]">{String(label)}<input value={String(value)} onChange={(event) => (setter as (value: string) => void)(event.target.value)} required={!optional} type={label === t.skeins ? "number" : "text"} min={label === t.skeins ? 1 : undefined} className="mt-2 min-h-12 w-full rounded-xl border border-[#DED6EA] px-4 text-sm font-normal outline-none focus:border-[#A875D2]" /></label>)}<label className="block text-sm font-semibold text-[#514A67]">{t.notes}<textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={2000} className="mt-2 min-h-28 w-full rounded-xl border border-[#DED6EA] px-4 py-3 text-sm font-normal outline-none focus:border-[#A875D2]" /></label><button disabled={loading} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#7438B7] px-5 text-sm font-semibold text-white disabled:opacity-60">{loading ? <Loader2 size={17} className="animate-spin" /> : null}{t.submit}</button></div> : <p className="mt-6 rounded-xl bg-[#FAF8FC] p-4 text-[#6E6582]">{t.login}</p>}{message ? <p role="status" className="mt-4 text-sm text-[#6E6582]">{message}</p> : null}</form></section></main>;
}
