"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Loader2 } from "lucide-react";
import { supabase } from "../supabase";

type Wanted = { brand: string | null; yarn_name: string | null; color: string | null; dyelot: string | null; skeins: number | null; description: string | null };
export default function EditWantedPage({ id, language }: { id: string; language: "en" | "pl" }) {
  const [userId, setUserId] = useState<string | null>(null); const [brand, setBrand] = useState(""); const [yarn, setYarn] = useState(""); const [color, setColor] = useState(""); const [lot, setLot] = useState(""); const [skeins, setSkeins] = useState(""); const [notes, setNotes] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const t = language === "pl" ? { title: "Edytuj ogłoszenie „Szukam”", back: "Wróć do ogłoszeń", brand: "Marka", yarn: "Nazwa włóczki", color: "Kolor / numer koloru", lot: "Dye lot (opcjonalnie)", skeins: "Ilość", notes: "Dodatkowe informacje", save: "Zapisz zmiany", missing: "Nie znaleziono ogłoszenia lub nie masz uprawnień do edycji.", required: "Uzupełnij markę, nazwę włóczki, kolor i ilość.", error: "Nie udało się zapisać zmian.", success: "Zmiany zostały zapisane." } : { title: "Edit yarn request", back: "Back to requests", brand: "Brand", yarn: "Yarn name", color: "Color / color number", lot: "Dye lot (optional)", skeins: "Quantity", notes: "Additional information", save: "Save changes", missing: "This request was not found or you do not have permission to edit it.", required: "Enter the brand, yarn name, color, and quantity.", error: "Could not save changes.", success: "Changes have been saved." };
  // Language changes reload the route text; the inline translation object is intentionally not a dependency.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { let mounted = true; async function load() { const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) { if (mounted) { setMessage(t.missing); setLoading(false); } return; } const { data, error } = await supabase.from("listings").select("brand, yarn_name, color, dyelot, skeins, description").eq("id", id).eq("user_id", session.user.id).eq("listing_type", "wanted").maybeSingle<Wanted>(); if (!mounted) return; setUserId(session.user.id); if (error || !data) setMessage(t.missing); else { setBrand(data.brand ?? ""); setYarn(data.yarn_name ?? ""); setColor(data.color ?? ""); setLot(data.dyelot ?? ""); setSkeins(String(data.skeins ?? "")); setNotes(data.description ?? ""); } setLoading(false); } void load(); return () => { mounted = false; }; }, [id, language]);
  async function submit(event: FormEvent) { event.preventDefault(); const count = Number.parseInt(skeins, 10); if (!userId || !brand.trim() || !yarn.trim() || !color.trim() || !Number.isFinite(count) || count < 1) { setMessage(t.required); return; } setSaving(true); setMessage(""); const { error } = await supabase.from("listings").update({ brand: brand.trim(), yarn_name: yarn.trim(), color: color.trim(), dyelot: lot.trim() || null, skeins: count, description: notes.trim() || null }).eq("id", id).eq("user_id", userId).eq("listing_type", "wanted"); setSaving(false); setMessage(error ? t.error : t.success); }
  const backHref = language === "pl" ? "/looking" : "/en/looking";
  return <main className="min-h-screen bg-[#F7F4FB] px-4 py-8 text-[#17142E] sm:px-6 sm:py-12"><section className="mx-auto max-w-2xl"><Link href={backHref} className="text-sm font-semibold text-[#7438B7]">← {t.back}</Link><form onSubmit={submit} className="mt-5 rounded-2xl border border-[#E8E1F0] bg-white p-6 shadow-[0_18px_55px_rgba(51,36,82,0.09)] sm:p-8"><h1 className="text-3xl font-bold">{t.title}</h1>{loading ? <p className="mt-6 flex items-center gap-2 text-[#6E6582]"><Loader2 size={18} className="animate-spin" />{language === "pl" ? "Ładowanie…" : "Loading…"}</p> : message === t.missing ? <p className="mt-6 text-red-700">{message}</p> : <div className="mt-6 grid gap-5">{[[t.brand, brand, setBrand, false], [t.yarn, yarn, setYarn, false], [t.color, color, setColor, false], [t.lot, lot, setLot, true], [t.skeins, skeins, setSkeins, false]].map(([label, value, setter, optional]) => <label key={String(label)} className="block text-sm font-semibold text-[#514A67]">{String(label)}<input value={String(value)} onChange={(event) => (setter as (value: string) => void)(event.target.value)} required={!optional} type={label === t.skeins ? "number" : "text"} min={label === t.skeins ? 1 : undefined} className="mt-2 min-h-12 w-full rounded-xl border border-[#DED6EA] px-4 text-sm font-normal outline-none focus:border-[#A875D2]" /></label>)}<label className="block text-sm font-semibold text-[#514A67]">{t.notes}<textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={2000} className="mt-2 min-h-28 w-full rounded-xl border border-[#DED6EA] px-4 py-3 text-sm font-normal outline-none focus:border-[#A875D2]" /></label><button disabled={saving} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#7438B7] px-5 text-sm font-semibold text-white disabled:opacity-60">{saving ? <Loader2 size={17} className="animate-spin" /> : null}{t.save}</button></div>}{message && message !== t.missing ? <p role="status" className="mt-4 text-sm text-[#6E6582]">{message}</p> : null}</form></section></main>;
}
