alter table public.profiles
  add column bio text
  constraint profiles_bio_length_check check (char_length(bio) <= 300);

create table public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  slot smallint not null check (slot between 1 and 6),
  title text not null check (char_length(title) between 1 and 100),
  description text check (description is null or char_length(description) <= 500),
  yarn_name text,
  yarn_brand text,
  image_url text not null,
  created_at timestamptz not null default now(),
  constraint projects_user_slot_unique unique (user_id, slot)
);

create index projects_user_created_at_idx
  on public.projects (user_id, created_at desc);

alter table public.projects enable row level security;

grant select, insert, update, delete on public.projects to authenticated;

create policy "Authenticated users can read projects"
  on public.projects for select to authenticated
  using (true);

create policy "Users can create their own projects"
  on public.projects for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own projects"
  on public.projects for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own projects"
  on public.projects for delete to authenticated
  using ((select auth.uid()) = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'project-images',
  'project-images',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do nothing;

create policy "Authenticated users can read project images"
  on storage.objects for select to authenticated
  using (bucket_id = 'project-images');

create policy "Users can upload own project images"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'project-images'
    and (storage.foldername(name))[1] = 'projects'
    and (storage.foldername(name))[2] = (select auth.uid()::text)
  );

create policy "Users can delete own project images"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'project-images'
    and (storage.foldername(name))[1] = 'projects'
    and (storage.foldername(name))[2] = (select auth.uid()::text)
  );
